/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative */

#ifndef _Included_com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
#define _Included_com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    setUpNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_setUpNative
  (JNIEnv *, jobject);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    getUserNameNative
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_getUserNameNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    setUserInfoNative
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_setUserInfoNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    setUserNameNative
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_setUserNameNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    isExistVehicleInfoNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_isExistVehicleInfoNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    generatePublicKeyNative
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_generatePublicKeyNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    extractSharedKeyNative
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_extractSharedKeyNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    getPinCodeSendDataNative
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_getPinCodeSendDataNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    createAuthKeyNative
 * Signature: (Ljava/lang/String;[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_createAuthKeyNative
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    deleteRegistrationKeyNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_deleteRegistrationKeyNative
  (JNIEnv *, jobject);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    stopRegistrationCryptionNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_stopRegistrationCryptionNative
  (JNIEnv *, jobject);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    deleteVehicleInfoNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_deleteVehicleInfoNative
  (JNIEnv *, jobject, jstring);

/* FPT #176134 S */
/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    deleteFileNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_deleteFileNative
  (JNIEnv *, jobject);

/* FPT #176134 E */
/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    tryAuthenticationNative
 * Signature: (Ljava/lang/String;[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_tryAuthenticationNative
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    decryptoReceivedDataNative
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_decryptoReceivedDataNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    encryptoSendDataNative
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_encryptoSendDataNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_panasonic_ais_VehicleCryptoServiceLib_VehicleCryptoServiceNative
 * Method:    stopAuthenticationDataCryptionNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_honda_connmc_NativeLib_NativeLibController_stopAuthenticationDataCryptionNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
